import { Text } from './types';

export const texts: Text[] = [
  {
    name: '1. Leseøvelse med a, b, l, k',
    lines: [
      'ba ab abba bak kabb kaba al la labb',
      'lakk bal blakk ak kakk kalk kala klakk',
      'kabal klabb alka lakka babla labba kakla aka kaka',
    ],
    signs: ['a', 'b', 'l', 'k'],
  },
  {
    name: '2. Leseøvelse med e, i',
    lines: [
      'be le ek el bel ble bek blek kleb blekk',
      'elle ekle ekkel lekke klekke',
      'alle lakke kalle alke bleke blakke',
      'klebe ebbe klebe bekle ballek',
      'ei eie bi bie li il ile ille lille',
      'bli bil bile bille kli kile ikke klikk',
      'klikke bel ble blikk leie eli leiebil',
      'bleik eik leike lilla leikebil',
      'eike leike akkeleie',
    ],
    signs: ['e', 'i'],
  },
  {
    name: '3. Leseøvelse med stor bokstav, punktum og komma',
    lines: [
      'Alle ble leie. Alle ble blakke. Ikke',
      'alle ble leie, Eli ble ikke lei. Ikke',
      'alle ble blakke, Ella ble ikke',
      'blakk. Eli lakka, Ella kalka, alle',
      'kakla. Alle la kabal. Alle la',
      'ikke kabal, Lalla la ikke kabal.',
    ],
    signs: ['E', '.', ','],
  },
  {
    name: '4. Leseøvelse med s',
    lines: [
      'sa asa se ese si ise sil sel sil',
      'lass lesse lisse saks sekk silke',
      'sklie blass kliss sei seile',
      'silke elske leske sleike Elise',
      'Sissel sklie skilisse',
    ],
    signs: ['s'],
  },
  {
    name: '5. Leseøvelse med m, o, u',
    lines: [
      'mamma amme Emma mel melk klem melke',
      'klemme mil lim slem slim slam mas',
      'masse kime samme slemme blemme kam',
      'Selma simla sommel',
      'Mamma skal lese i Selmas bok. Mamma ble',
      'lei Selmas bok. Selma ble ikke lei boka',
      'si. Emma maa male, Mia maa lime. Mamma',
      'ble lei Mias kliss. Mia skal ikke lime',
      'bo bok bol bolle bolk blokk klok klokke',
      'lokke kolle mo om molo kom komme komma',
      'bomme somle Ole sol Solo skole',
      'Oslo klo lomme olm',
      'Ole ble lei Eli. Eli ble like lei blakke',
      'Ole. Ella ble ikke lei Ola. Ola skal',
      'like Laila. Sissel ble lei Oles bok. Ole',
      'ble ikke lei skoleboka si. Eli skal seile. Ole',
      'ble lei slik seilas i sola. Ole skal',
      'bokse i Oslo. Ole boksa ikke, Ole',
      'slo. Molla kom som sola i Oslo.',
      'bu ku uke lue ule luke lukke ulke',
      'kule bule ublu mule mulle aula auke',
      'allmue smule ussel bukk buk Ulla',
      'sulle skulle ussel lus sull luske',
      'Ulla skal seile. Ole ble lei Ullas',
      'seilas. Ola skal ikke kullseile. Ulla',
      'ble lei ullbuksa, Ulla ble ikke lei lua',
      'si. Ole skal sulle, sulle, sulle. Ulla',
      'ble lei Oles usle sull, Ulla ble ikke',
      'lei kul musikk. Ussel blues, sa Ullas Ole.',
    ],
    signs: ['m', 'o', 'u'],
  },
  {
    name: '6. Leseøvelse med p, r, v',
    lines: [
      'ap pappa papp ape Epa pippi lapp',
      'klappeklippe opp kopp sopp osp sope pus',
      'pusse suppe spille slippe pusle plopp',
      'klopp slips suppepose',
      'Pappa skal ikke klippe papp. Pelle ble',
      'ikke lei popmusikk. Pelle skal spille',
      'pop. Pappe ble lei sleipe Pelles pop. Pappa',
      'ble ikke lei posesuppe. Suppa skal spises. Pelle',
      'ble lei soppsuppe. Pelle skal ikke plukke',
      'sopp i pose, Pelle skal plukke sopp i kopp.',
      'ar ra rar ara rare rer ber bre rir blir or',
      'ro ror bror ur bur brur lur sur skur bruser',
      'rebuser per biler krukker spreller kor krok krukker',
      'Roar er rar som ble lei sei. Roar ble ikke like',
      'lei sik. Elsa ble ikke lei sei. Elsa ble lei',
      'pir. Alle liker skrei. Per liker ikke uer i',
      'krukker. Per er sprek. Per spaserer',
      'masse. Rare Roar spaserer ikke mer. Rare',
      'Roar bare ruller.',
      'av va kva kval lav leve liv vil vill vel',
      'kvile rav var arv rev rive rov over sove',
      'vik kiv kvikk vov avviker ukeverk arvelov',
      'veske sviske sveiv',
      'Eva vil seile over Vorma. Vivvi vil skrive',
      'vers. Vesle Vivvi skriver vakre vers. Ivar',
      'skriver bare ville svar. Sverre ville ikke leie',
      'Volvo. Sissel vil ikke vike vekk. Ove vil',
      'bare sove. Eva vil svinge svepa over',
      'Ove. Eva vil veve selv.',
    ],
    signs: ['p', 'r', 'v'],
  },
  {
    name: '7. Leseøvelse med å',
    lines: [
      'å ål lå blå bål åk kål må åme på rå',
      'år åre så ås lås slå skål krål vår uår',
      'sår skrå skår såpe bås blåse',
      'kåre kråke åker råke',
      'Pål må slå på lokk. Åse vil ikke slå på',
      'lokk, Åse må spille på lur. Ulla vil ikke',
      'blåse på lur, Ulla vil kråle. I år må Pål',
      'komme over åser i Åseral. Åse rår over Kåre, Åse',
      'må låse Kåres bås. I år må Kåre så fem',
      'mål åker på Kåsa.',
    ],
    signs: ['å'],
  },
  {
    name: '8. Leseøvelse med g',
    lines: [
      'ga egg gi og ugg bag begge gikk også',
      'ugle vugge suge rugge gurgle gulpe',
      'pugge ligge lugge gul glugge rug',
      'gru mugg iglo glise mugge vugge grue gull',
      'Eg er lei å gå på gamle golv. Vi må velge',
      'belegg. Gå og se på belegg og velg lakk til golv',
      'og vegg. Åge og Gro vil ha egg som pålegg. Gro',
      'gir Georg gamle lugger. Egil gir Giggi',
      'gode gaver. Geir ligger i vogga og Gro',
      'vogger Geir. Sigve seglar og sigrar.',
    ],
    signs: ['g'],
  },
  {
    name: '9. Skrivøvelse med j, h',
    lines: [
      'ja aj bj gj kj jeg bjelle bjelke kjelke',
      'kjeller lilje ljå jåle sjå jakke kjake jukse',
      'sju jul juli sjuk oj olje jolle Jeriko kjeks',
      'kjeller sjal bjelle sjau skjul',
      'Jeg vil velge Jaguar og ikke Volvo. Jakob',
      'og Maja vil ake på kjelke. Jakob er lei av å',
      'spille jojo. Mirjam vil jage Maja og gjemme Jakob.',
      'Julie kjem ikkje i jula. Sjur var ikkje sjuk sjølv',
      'i sju veker, Sjur var berre sjuk i juli.',
      'ha aha haha Beha hage hege hige hegg hogge hekk',
      'hekle hjalp hjelpe håpe hår hvem hva hvor her',
      'hjelp hjem hjul hjå hilse heis hvile',
      'Helge hugsa hesten Heimhug som berre ville ha',
      'havre. Her veks haugar av hegg hjå ho Halgerd. Ho',
      'Helga helsa på han Hårek frå Hamar. Hils til',
      'Helga og Helge fra Hilmar som har hus og hjem',
      'på Hegra. Husk på Hege og Halvor.',
    ],
    signs: ['j', 'h'],
  },
  {
    name: '10. Skriveøvelse med f, d',
    lines: [
      'fe fele felle fil fille flik klaff fag flagg',
      'folk flokk fra for paff puff uff huff furu skuff',
      'fjell fjes jafs kaffe skuff loff blaff fosfor fisk fikse skiferie',
      'Olaf fikk fem fisker fra Flisa. Med klaff kan',
      'du ta alle i samme jafs. Joffe fikk fele av farmor og',
      'farfar. Joffe ville hive fillefela. Farfar fikk kaffe',
      'av Joffe. Joffe leste om Fiffi og Foffo for',
      'farfar. Av farmor får Joffe loff. Joffe jafser loff.',
      'bad bod da Ada de Edda Ida dag gadd daff dal del',
      'ledd kledd hadde Hilde holde lodd både nådde',
      'sådde diadem odde dadda Odd med ord',
      'Odd og Hilde bodde i Odda i sju år. Frode',
      'likte seg bedre på vidda. Ved Dagglad var vi',
      'veldig daffe vi gadd ikke å gå videre. Odd og Ida',
      'hadde dadda fra Odda. Da bodde dadda i',
      'Heddal. Odd og Ida har gode dager med dadda.',
    ],
    signs: ['f', 'd'],
  },
  {
    name: '11. Skriveøvelse med t, æ',
    lines: [
      'sta ste sti sto ost sot sist kost tosk skotsk liste',
      'stille stelle stulle usselt tatt tett otto stutt rast',
      'sats trist struts sitter stekt titt tett trut trost',
      'Otto og Totto tek tidt stutte turar til tante Tora',
      'på Otta. Det er stas med togtur til Otta for Otto',
      'og Totto. Otto og Totto satt tett i tett på toget til',
      'Otta. Tante Tora på Otta tar telefon til Otto og',
      'Totto hver torsdag. Slutt med dette tullet.',
      'bæ bær ære lære kjære sær tær stær være uærlig',
      'særlig pære fjær gjær sekretær populær klær fæl',
      'færre væske pæl trær knær skjære blæ',
      'Ære være dem som ikke er sære. Dere som vil lære',
      'å plukke bær, er ikke sære. Vår kjære sekretær måtte',
      'lære å plukke bær i særlig dårlig vær. Her skal det',
      'være færre trær. Lærer Sæther vil lære vår',
      'kjære sekretær å plukke bær.',
    ],
    signs: ['t', 'æ'],
  },
  {
    name: '12. Skriveøvelse med n',
    lines: [
      'Anna Anne Ninni enno ennå noen nokon min men',
      'mon unna Unni inne ingen mann kunne nesten',
      'nå Ingunn Inger tann minne neimen',
      'Nina nikker til Anne og snakker med Nils. Ninni',
      'nekter å snakke med Nina. Nunnu unner Unni',
      'en blund under dunen. Tante Ina er munter. Inger',
      'finner nesten ingen ting. Inger og Mona er nære venninner.',
    ],
    signs: ['n'],
  },
  {
    name: '13. Skriveøvelse med q',
    lines: [
      'IQ aqua Quale qvale patetique arabesque qvo',
      'Quale og Quist danser arabesque patetique. Quale',
      'har IQ på nitti. Quist vet ikke sin',
      'IQ. Med bra IQ husker du sikkert også q.',
    ],
    signs: ['q'],
  },
  {
    name: '14. Skriveøvelse med c, x',
    lines: [
      'ca. cm cl cd etc. flax extra mix lux Caba',
      'Bach Bruch taxi Alexander Cecilie Prix celle',
      'cello Plax Cocca Cola Cox Fox',
      'Cecilie drikker ca ti cl CoccaCola hver dag. Hun',
      'vil ha Cola fra Prix. Jeg kan lytte til Bach,',
      'Cox, Bruch etc. Cecilie spiller cello på',
      'Caba. Conrad sender en fax og bestiller Flax',
      'og Extra. Alexander tar en taxi til Coch.',
    ],
    signs: ['c', 'x'],
  },
  {
    name: '15. Skriveøvelse med y, z',
    lines: [
      'by bly ly fy fly kry lys syl hyl mye zu zum zur',
      'jazz pizza mezzo yte yste syte zabine fazer',
      'lyn yatzy Zala Ziba tyst styr styrte stryke Mozart',
      'Ylva vil spille jazz sammen med Zabine. Sylvi',
      'vil heller spise pizza og spille Yatzy. Sylvi',
      'nyter Fazer, og synes det er nydelig. Sylvia',
      'er mezzo, og kan spille pizzicato. Fritz må gå',
      'til dyrlege Prytz med Ziba.',
    ],
    signs: ['y', 'z'],
  },
  {
    name: '16. Skriveøvelse med ø',
    lines: [
      'bø kø øk løk klø bøk øs søk øl søl løs ør bør',
      'øre bøy føy gøy høy køye møye tøye øve',
      'søle søyle føle føye nøle nøye bølle bøye',
      'Frøydis bør gjøre øvelsen før Bjørn gjør den. Øystein',
      'bør være nøye med det nye tøyet sitt. Bjørg',
      'bør søke på økonomi i Ørsta før hun flytter østover',
      'til Bø. Øv nøye på bøyning før du gjør øvelsen',
      'på lørdag. Øvelser er gøy.',
    ],
    signs: ['ø'],
  },
  {
    name: '17. Skriveøvelse med w',
    lines: [
      'we how who Willy Wang swing Swix Wenche Wien Winge',
      'Wagner Weber word windings two VW',
      'www. Lewi Wenche twå twål show',
      'Wenche Wang vil danse swing etter Wild Wood',
      'Flower. Willy vil ikke til Wien, han vil høre',
      'Wagner i Warszawa. Lewi Winge går alltid på blå',
      'Swix. Du kan søke etter Weber på www. Wenche',
      'vil kjøpe twist til Willy på Kiwi.',
    ],
    signs: ['w'],
  },
  {
    name: '18. Ymse setninger',
    lines: [
      'Apene i Afrika i alle aldere er akrobater, og de akrobaterer mens andre applauderer.',
      'Både Bodil Brun og broren til biskopen i Bodø bruker blå blyant.',
      'Coca Cola er ca cent cl på Caba et co.',
      'Du datt dypere og dypere den dagen du drog deg dit.',
      'Ellen Eliassen eier en enestående enebolig på Elverum.',
      'En fin fornem frue fra Frogner fikk fint følge fra Fana til Flekkefjord.',
      'Gode gamle gubbar greier godt å gå på glatta gjennom glisne grender med gode gangvegar.',
      'Heile hopen hugsa han Hans som i hovmot heldt hovudet høgt mot himmelen.',
      'Vi vil sikkert finne steinete stier til vi svinger inn på den fine veien der vi vil sitte i fin bil.',
      'Jammen gjør Jan Jensen og jeg tjue sjeldne jobber på sju dager i juni.',
      'Kari kan kanskje koke kakao og bake kokuskake på kjøkkenet til kalaset i kveld? La lille Lillian få i lekse å legge lag på lag i lageret på låven.',
      'Mange må mene at mamma og mormor må mene mye mer om sommeren.',
      'Nina og Anna snakker og nikker når Ninni og Nanna nikker og snakker.',
      'Otto og Oda er ofte på Otta der også onkel Ole oppholder seg onsdag.',
      'Per og Pål stopper opp og popper popcorn i kopp.',
      'Qvale og Qvist danser arabesque patetique på Quitz.',
      'Runde rare ringer romler rundt i rørene på rommet.',
      'Så sessa vi oss sammen om storbordet i spisestua og spiste posesuppe.',
      'Ta stolen tett inntil telefonen og telefoner til tante Tone på Toten.',
      'Unnskyld at Unni uteble, men uka er ute uten uhell.',
      'Vi var veldig viktige ved hvert veivalg og ved hver sving.',
      'How much wood would a wood-chap if a wood-cap would chap wood?',
      'Med flax fixer du en extra taxi til Alexander når han skal på Prix.',
      'Synnøve syntes synet var synlig forstyrrende for øynene i skyet flyvær.',
      'Zala og Ziba er gale etter pizza, men de knurrer stygt når Zabine Malzas synger jazz og når Elizabeth spiller Yatzy.',
      'Vær ikke sær, men vær ærlig og lær om bær av din kjære lærer Sæther i særlig vakkert vær.',
      'Bjørn bør gjøre prøven før Sørebø kjører østover med brød til Bø. Nå får Pål gå på lånte såler så han håper å nå målet før påske.',
    ],
  },
  {
    name: '19. Skriveøvelse med 1, 2, 3',
    lines: [
      '1 11 111 2 22 222 3 33 333 123 321 231 312 213',
      '132 1123 1232 1213 1223 1231 1232',
      '1233 1321 13222 1323 1332',
    ],
    signs: ['1', '2', '3'],
  },
  {
    name: '20. Skriveøvelse med 7',
    lines: ['7 77 777 17 27 37 71 72 73 1177 1277', '1377 1712 1713 1717 1721 1723', '1727 1732 1771 1772 1773 1777'],
    signs: ['7'],
  },
  {
    name: '21. Skriveøvelse med 5, 9',
    lines: [
      '5 55 555 15 25 35 55 75 51 52 53',
      '55 57 1515 1525 1525 1555 1575 1155',
      '1255 1355 1755 1551 1552 1553 1555 1557',
      '9 99 999 19 29 39 59 79 99 91 92 93',
      '95 97 99 1991 1992 1993 1995 1997',
      '1999 1951 1953 1955 1957 1959',
    ],
    signs: ['5', '9'],
  },
  {
    name: '22. Skriveøvelse med 0, 8',
    lines: [
      '0 10 100 20 200 30 300 50 300 70 700',
      '90 900 101 102 203 105 107 109 110',
      '120 130 150 170 190 2000 2001 2002 2003',
      '8 88 888 18 28 38 58 78 88 98 81 82 83',
      '85 87 88 89 1818 1828 1838 1858 1878 1888',
      '1898 1881 1882 1883 1885 1887 1888 1889',
    ],
    signs: ['0', '8'],
  },
  {
    name: '23. Skriveøvelse med 4, 6',
    lines: [
      '4 44 444 14 24 34 40 41 42 43 44 45 47 48',
      '49 54 64 74 84 94 1400 1414 1424',
      '1434 1770 1444 1454 1474 1484 1494',
      '6 66 666 16 26 36 46 56 60 61 62 63 64 65',
      '66 67 78 69 76 86 96 100 1616 1626 1636',
      '1646 1656 1666 1676 1686 1696 1660 1661',
      '1662 1663 1664 1665 1666 1667 1668 1669',
    ],
    signs: ['4', '9'],
  },
  {
    name: '24. Skriveøvelse med desimaltall',
    lines: ['2,5 1,25 3,14 4,75 10,34 16,27 36,9 3,141526'],
  },
  {
    name: '25. Skriveøvelse med skilletegn i tall',
    lines: [
      '07.15 09.45 11.35 13.30 15.05 17.10 19.19 21.55 23.03',
      '09.04.1940 08.05.1945 25.09.1972 01.01.2000 24.06.02 29.07.03 24.12.04',
    ],
  },
  {
    name: '26. Skriveøvelse med spørretegn og utropstegn',
    lines: [
      'Er det onsdag i dag? Det er helt sikkert onsdag i dag!',
      'Har du lyst til å være med på Caba og spise pizza?',
      'Jeg vil gjerne være med på Caba, og jeg er kjempeglad i pizza! Er du sint? Nei! Jeg finnes ikke sint!',
      'Er du glad i dag? Jeg er kjempeglad i dag!',
      'Er Bjørn 8 år? Bjørn er 8 1/2 år!',
      'Møtes vi 19.30? Vi møtes presis 19.30!',
      'Er Rimi åpent klokka 20.00? Rimi har åpent helt til 21.00!',
      'Kan jeg ringe 22 02 95 00? Du må ringe 22 02 95 28!',
      'Tror du dette går bra? Ja, dette går helt sikkert bra!',
    ],
    signs: ['?', '!'],
  },
  {
    name: '27. Skriveøvelse med kolon og anførsel',
    lines: [
      'Da sa hun: "Dette var gøy!"',
      'Du bør høre: "Cox", "Dickens", "Skyldig" og "Løslatt på prøve".',
      'Slik står det: "Jeg vil gjerne være med", sa hun og rødmet. "Jeg har så allikevel ikke noe å gjøre i kveld", la hun til.',
      'Deretter sa Øyvind: "Dette stedet", han pekte på noe som nærmest så som en steinrøys, "dette stedet var mine oldeforeldres hjem".',
      'Da Wenche ropte: "Ziba"! "Zala"! "Zero"! kom tre hunder av typisk "blandingsrase" løpende.',
    ],
    signs: [':', '"'],
  },
  {
    name: '28. Skriveøvelse med parentes',
    lines: [
      'I dag (onsdag) må vi jobbe lenge (til 18.30).',
      'Butikken (Rimi) har åpent til 23 (18).',
      'Renate (min søster) er i utlandet (Wien).',
      'Min bror (Roger) er hjemme (i Drammen) hele tiden. Vi bodde i Lima (hovedstaden) under hele oppholdet. Det er få (nesten ingen) som ville gjøre noe.',
      'Du kan ta bussen (45) til Majorstua.',
    ],
    signs: ['(', ')'],
  },
  {
    name: '29. Skriveøvelse med bindestrek',
    lines: [
      'Anne-Lise er "kul"! Hun er fra Aust-Agder (Birkeland) og er midt i',
      '20-årene. Hun har en gutt som heter Tor-Alexander (2) og hun',
      'samboer med Jan-Erik (28). Hun tar en 3-årig utdanning',
      'på "Aften-skolen" (privatskole), så hun har',
      'nok å gjøre. Allerede som 30-åring vil',
      'hun (kanskje) ha en stilling som edb-konsulent.',
    ],
    signs: ['-'],
  },
];
